CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   dtype VARCHAR(31),
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   income DECIMAL NOT NULL,
   password VARCHAR(255) NOT NULL,
   CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user" ADD CONSTRAINT uc_user_cpf UNIQUE (cpf);

ALTER TABLE "user" ADD CONSTRAINT uc_user_email UNIQUE (email);


CREATE TABLE operator(
user_id int primary key references "user"(id)
);


CREATE TABLE account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   operator_id BIGINT,
   account_balance DECIMAL,
   created_at date NOT NULL,
   CONSTRAINT pk_account PRIMARY KEY (id)
);

ALTER TABLE account ADD CONSTRAINT FK_ACCOUNT_ON_OPERATOR FOREIGN KEY (operator_id) REFERENCES operator (user_id);


CREATE TABLE transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   receiver_id BIGINT,
   date date NOT NULL,
   transaction_type VARCHAR(255) NOT NULL,
   operation_type VARCHAR(255) NOT NULL,
   issuer_id BIGINT,
   "value" DECIMAL NOT NULL,
   account_id BIGINT,
   CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE transaction ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);

ALTER TABLE transaction ADD CONSTRAINT FK_TRANSACTION_ON_ISSUER FOREIGN KEY (issuer_id) REFERENCES operator (user_id);

ALTER TABLE transaction ADD CONSTRAINT FK_TRANSACTION_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES operator (user_id);


CREATE TABLE bank_statement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   account_id BIGINT,
   beginning date NOT NULL,
   "end" date NOT NULL,
   CONSTRAINT pk_bankstatement PRIMARY KEY (id)
);

ALTER TABLE bank_statement ADD CONSTRAINT FK_BANKSTATEMENT_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);